--- 
 - become: true
   hosts: all
   name: "Copy file"
   vars: 
    dump_dir: "C:\\Users\\Administrator\\Downloads\\test2"
    myfile: "C:\\Users\\Administrator\\Downloads\\test1"
   tasks: 
    - name: "fetch file"  
      ansible.builtin.fetch: 
       dest: "{{ dump_dir }"
       src: "{{ myfile }}"
      
